# Prefix
unbind C-b
bind C-a send-prefix

# 鼠標支持
set -g mouse on

# 256色
set -g default-terminal "tmux-256color"

# 歷史記錄
set -g history-limit 500000

# 快速刷新
set -sg escape-time 0

# 分屏
bind | split-window -h
bind - split-window -v

# Vim風格切換
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Vim風格調整窗口大小
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# 重新加載
bind r source-file ~/.config/tmux/tmux.conf

# 窗口編號
set -g base-index 1
setw -g pane-base-index 1

# 狀態欄
set -g status-position bottom

# 真彩色支持
set-option -sa terminal-overrides ",xterm-256color:RGB"

# 自動重命名關閉
set-option -g allow-rename off

# 必備插件
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.tmux/plugins/tpm/tpm'
